### ISSUE TITLE
When linking to a page while the cursor is on the right most side of the content, the content under the page selection will visually shift to the left

### ISSUE THREAD

**Issue by battlingthegods** [rcvd/roam-css-system#14]
The content area on the right side ends where the `+` is. The page suggestion box should float to the left, instead of staying in the same position and visually pushing the content under it to the left. 

<img width="449" alt="" src="https://user-images.githubusercontent.com/3187653/121927940-ec898000-cd3f-11eb-849f-20343778d803.png">

**Comment by rcvd** [comment]
You are right, but this can't be changed within the CSS system but must be fixed upstream.
