### ISSUE TITLE
Attributes are weighted bold

### ISSUE THREAD

**Issue by battlingthegods** [rcvd/roam-css-system#17]
I know this is what Roam does itself, but given the theme's fonts, the bold attributes really visually stand out in a non-pleasing way, so I'd love to see them styled differently, maybe like so:

```
.rm-attr-ref {
  font-weight: normal;
  text-decoration: underline;
  text-decoration-style: dotted;
  margin-right: 0.125em;
  }
.rm-attr-ref:hover {
  text-decoration-style: dashed;
}
```

**Comment by rcvd** [comment]
Thank for you suggestion, I'll add CSS Selectors for this, so it can be easily changed in the final version.
