### ISSUE TITLE
Increase base font size

### ISSUE THREAD

**Issue by battlingthegods** [rcvd/roam-css-system#18]
I'd love to see the base font size increased to 16px, mostly for selfish reasons as my eyes start to show signs of ageing 😬Also, it's the default font size in browsers, anyway.

(I know I can change font size in browsers and in the app, but doing so will also change things like the width of the left sidebar etc.)

**Comment by rcvd** [comment]
Not sure if I should change the base font size but at least I will add a CSS Selector to easily modify it.
