### ISSUE TITLE
Font not rendering in Brave Browser

### ISSUE THREAD

**Issue by c-chae** [rcvd/roam-css-system#19]
works fine in both macOS app and Safari browser. Just not in Brave. Not sure if this issue replicates in Chrome or any other browsers.

This is how Brave shows the site:
<img width="1680" alt="CleanShot 2021-06-14 at 13 19 25@2x" src="https://user-images.githubusercontent.com/57276522/121939915-27c18a00-cd13-11eb-9e55-c55eb3934832.png">

This is how Safari shows the site:
<img width="1680" alt="CleanShot 2021-06-14 at 13 17 36@2x" src="https://user-images.githubusercontent.com/57276522/121939709-e7faa280-cd12-11eb-9bb1-2a5069ff5c96.png">

This is how macOS app shows the site:
<img width="1680" alt="CleanShot 2021-06-14 at 13 20 44@2x" src="https://user-images.githubusercontent.com/57276522/121940080-563f6500-cd13-11eb-8dba-0927754a4063.png">

**Comment by rcvd** [comment]
Please try again and report back. Can't reproduce this in Brave nor Chrome.

**Comment by c-chae** [comment]
looks like it's working now!
