### ISSUE TITLE
Not Responsive with roam/css

### ISSUE THREAD

**Issue by Yulin-Rog** [rcvd/roam-css-system#27]
Dear Alexander, 

Hi there, thanks for making such a great minimal theme! But I'm seeing some issues from using native [[roam/css]] and css block to import the link. And I tried two of my Roam account, all of them won't generate the theme. 

But it works perfectly well with chrome extension "stylus". 

Would you mind having a look at the issue please? Thanks!!

<img width="1015" alt="Screen Shot 2021-06-21 at 4 14 11 PM" src="https://user-images.githubusercontent.com/74748709/122729412-b9993c00-d2ab-11eb-8588-306cf9ddeff7.png">

**Comment by rcvd** [comment]
Please check if @import works without any other block on roam/css. If it works, then something is wrong with your other blocks (e.g. missing semicolon or bracket inside the code blocks). Please get back with the result.

**Comment by Yulin-Rog** [comment]
Hi there, I checked with the import link. In fact, it's not working with any other css 😭

**Comment by rcvd** [comment]
Have your tried putting it at the top of the page?

**Comment by Yulin-Rog** [comment]
Yes!! That works extremely well now :) Thank you so much for helping me out!!
