### ISSUE TITLE
Smartblocks menu not readable on dark theme

### ISSUE THREAD

**Issue by surrjon** [rcvd/roam-css-system#28]
I know this isn't native Roam, but a lot of people use Roam42 and Smartblocks.
Currently the menu looks like this: 
Smartblocks: https://share.getcloudapp.com/mXurrXjr
It's hard to read, light gray on white.

I'd love for it to look like the Templates menu with black background:
Templates: https://share.getcloudapp.com/rRujjRPb

Possible to change in the theme? Or do I need to get with the Smartblocks folks?

**Comment by rcvd** [comment]
First version released, take a look and tell me if you are missing something as I'm not using Roam42

**Comment by shawnyeager** [comment]
I'm seeing the same. Here's a screenshot taken minutes ago after a reload to assure latest version of the theme.
![Screen Shot 2021-06-22 at 10 31 59 PM](https://user-images.githubusercontent.com/980297/123002671-12e79500-d3aa-11eb-8109-07eb85978f59.png)

**Comment by rcvd** [comment]
How do you toggle that menu?

**Comment by edshamis** [comment]
Ctrl+P

**Comment by rcvd** [comment]
Fixed, I leave this issue open, in case that we have more unthemed elements in roam42

**Comment by edshamis** [comment]
![210623-212453](https://user-images.githubusercontent.com/47914518/123149178-aaf88380-d469-11eb-8b89-d746c87a29c7.png)
Same for help shortcuts

**Comment by rcvd** [comment]
fixed

**Comment by edshamis** [comment]
Btw huge thank you! It's the first time I feel at home in Roam)

**Comment by owenmcfadzen** [comment]
Thank you for the quick fix on this, it's amazing to see it get polished. iA has been my safe place for a long time and now Roam is really starting to become that too and it's thanks to you.

**Comment by surrjon** [comment]
Wow, sorry these emails were going into my spam folder. Fixed now.

I also see it fixed. Thanks Alexander for making this beautiful theme and
quick edits!

**Comment by edshamis** [comment]
Missing background for switchers in settings 
![210624-150849](https://user-images.githubusercontent.com/47914518/123260517-53f0be00-d4fe-11eb-8991-44f3034e32cd.png)

**Comment by rcvd** [comment]
Should be fixed now
