### ISSUE TITLE
Blockquotes in block references hovers aren't readable in dark mode

### ISSUE THREAD

**Issue by battlingthegods** [rcvd/roam-css-system#29]
They look great in light mode! Not so much in dark mode.

<img width="440" alt="Bildschirmfoto 2021-06-23 um 12 24 41" src="https://user-images.githubusercontent.com/3187653/123081465-4532da00-d41e-11eb-8179-0342326339c0.png">

Also, thank you for this fantastic theme.

**Comment by rcvd** [comment]
Could you please describe a little bit more what you have done to get this result?

**Comment by battlingthegods** [comment]
Why yes, of course: I just hyperlinked a ((block referenced)) blockquote so it shows a preview on hover:

<img width="201" alt="Bildschirmfoto 2021-06-23 um 18 46 56" src="https://user-images.githubusercontent.com/3187653/123136818-a4f7a800-d453-11eb-903b-2090ce5a4d98.png">

<img width="353" alt="Bildschirmfoto 2021-06-23 um 18 47 00" src="https://user-images.githubusercontent.com/3187653/123136820-a5903e80-d453-11eb-8e25-ccd85bc58f3f.png">

Mouse over:

<img width="228" alt="Bildschirmfoto 2021-06-23 um 18 47 06" src="https://user-images.githubusercontent.com/3187653/123136822-a628d500-d453-11eb-89a8-1a3783faa020.png">

**Comment by rcvd** [comment]
Fixed
