### ISSUE TITLE
Missing border and background for buttons 

### ISSUE THREAD

**Issue by edshamis** [rcvd/roam-css-system#30]
![210624-212002](https://user-images.githubusercontent.com/47914518/123313533-481eef00-d532-11eb-9ea7-f6ec3388e003.png)
![210624-212030](https://user-images.githubusercontent.com/47914518/123313540-49501c00-d532-11eb-94c9-1ec95d1f083f.png)
![210624-212042](https://user-images.githubusercontent.com/47914518/123313542-49501c00-d532-11eb-9975-168021b52dc7.png)

**Comment by rcvd** [comment]
Is this using Roam42? How did you create the buttons?

**Comment by edshamis** [comment]
New Roam native button:
  {{x-template-button: ((8MMdZyxue))}}
Smartblock button:
  {{⇥🕞:42SmartBlock:End time}}

Actually anything inside {{..}} is a button

**Comment by edshamis** [comment]
Nothing changed

**Comment by rcvd** [comment]
Have you tried reloading your graph (View -> Reload Page / View -> Reload)? 

<img width="749" alt="Screenshot 2021-06-24 at 21 11 31" src="https://user-images.githubusercontent.com/12938875/123319525-cd090900-d530-11eb-92e6-1a51e1788840.png">

**Comment by edshamis** [comment]
Sure, reloaded + disabled all css & js
Still nothing new

**Comment by rcvd** [comment]
I've created the button with `{{button}}` - nothing else. Not sure if the current CSS select works on buttons from smart blocks. Could you please re-check that `{{button}}` is still not working?

**Comment by edshamis** [comment]
Oh, yes, this one works, but not the others

**Comment by rcvd** [comment]
Can you show me how you created the other buttons as I am not using Roam42?

**Comment by mandliya** [comment]
I also have the same issue.  The button looks like this for a smartblock (roam42)

![image](https://user-images.githubusercontent.com/4503796/123342792-4559d500-d505-11eb-922f-5d0f590205ac.png)

and this is how I create button.

`{{Awe Inspiring :42SmartBlock:Night Sky Image}} `

**Comment by edshamis** [comment]
![210625-055811](https://user-images.githubusercontent.com/47914518/123363070-71636d80-d57a-11eb-84ce-84e713b21293.png)

These don't work

New Roam native button:
{{x-template-button: ((8MMdZyxue))}}

Smartblock button:
{{⇥🕞:42SmartBlock:End time}}

And new issue is introduced — gap below New Roam native button (Daily Agenda)
