### ISSUE TITLE
Questions about CSS system

### ISSUE THREAD

**Issue by manfrombar** [rcvd/roam-css-system#32]
Sorry to ask you such basic questions.
Can you add some more examples to your graph? For instance,

How can I change the color of different tags?
How can I change the general font in iA Quattro theme, where I can find a list of names of fonts?

Many thanks and congratulations for the great job done!!!!

**Comment by rcvd** [comment]
https://roamresearch.com/#/app/css-system/page/MCARgO70I

Have fun

**Comment by manfrombar** [comment]
Thanks a lot!!!!!!!
Change fonts links it doesn’t works



Manel Puntí

**Comment by rcvd** [comment]
Sorry? Do you want to include additional fonts (like google fonts)?

**Comment by manfrombar** [comment]
Sorry,
I mean, in your graph the external links doesn’t works





Manel Puntí
Music Distribución & Algam Ibérica
CEO
Phone  : (34) 934 221 811
Mobile : (34) 609 488 294
Skype : manel.punti1

Aviso legal: Este mensaje, incluidos sus ficheros adjuntos, contienen información confidencial, dirigida a un destinatario y con una finalidad específica protegida por la Ley. Le informamos que si Usted no es el destinatario del mismo, deberá eliminar éste mensaje, quedando estrictamente prohibida cualquier divulgación, copia o distribución de su contenido, así como desarrollar o ejecutar cualquier tipo de acción basada en su contenido. Si Usted es el destinatario, el uso de la información que ha recibido, deberá estar limitado a la finalidad específica por la cual se le ha enviado.

**Comment by rcvd** [comment]
You mean changing the color of external links doesn't work? Have your tried it like this:

<img width="754" alt="Screenshot 2021-06-25 at 17 36 01" src="https://user-images.githubusercontent.com/12938875/123449331-db602f00-d5db-11eb-9e62-f3fc6b0caf4b.png">

**Comment by rcvd** [comment]
Had to replace it with a description because the block references will change on every import. Hope it's useful anyways

**Comment by manfrombar** [comment]
Thanks again!!!!!
Great, great job!!!!!

Enviado desde mi iPhone

**Comment by manfrombar** [comment]
Hello
Do you know why fw-reference it doesn’t works?
I want to increase the font size in the page-title of linked referenced pages. I have added fw-reference, but no changes at all.
Thanks





Enviat des del meu iPad

> El 25 juny 2021, a les 21:26, Manel Punti ***@***.***> va escriure:
> 
> ﻿Thanks again!!!!!
> Great, great job!!!!!
> 
> Enviado desde mi iPhone
>

**Comment by rcvd** [comment]
fw is for the weight, fs is for the size. 

<img width="649" alt="Screenshot 2021-06-27 at 13 25 57" src="https://user-images.githubusercontent.com/12938875/123542676-38c6be00-d74b-11eb-9e15-dafafdbdea4c.png">

**Comment by manfrombar** [comment]
I know, but I want to change the weight. How can I do it?

Manel Punti
CEO - Music Distribución & Algam Ibérica
C/Garcilaso 11, Barcelona 08027
Phone : +34 934 221 811 - Mobile : +34 609 488 294
***@***.*** - www.musicdistribucion.com ( http://www.musicdistribucion.com )

facebook ( https://www.facebook.com/musicdistribucion/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature ) twitter ( https://twitter.com/musicdistrib?lang=ca&utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature ) youtube ( https://www.youtube.com/user/musicdistribucion?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature ) linkedin ( https://es.linkedin.com/company/music-distribuci-n_3?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature )

Aviso legal: Este mensaje, incluidos sus ficheros adjuntos, contienen información confidencial, dirigida a un destinatario y con una finalidad específica protegida por la Ley. Le informamos que si Usted no es el destinatario del mismo, deberá eliminar éste mensaje, quedando estrictamente prohibida cualquier divulgación, copia o distribución de su contenido, así como desarrollar o ejecutar cualquier tipo de acción basada en su contenido. Si Usted es el destinatario, el uso de la información que ha recibido, deberá estar limitado a la finalidad específica por la cual se le ha enviado.

**Comment by rcvd** [comment]
I've updated the CSS system to allow you to change the weight. Should work now after a reload.

**Comment by rcvd** [comment]
You can always look up all available variables in the public roam graph. If you are missing something just drop me a note.

<img width="732" alt="Screenshot 2021-06-27 at 13 40 19" src="https://user-images.githubusercontent.com/12938875/123543103-4da45100-d74d-11eb-9752-f9a82c62c3d3.png">
