### ISSUE TITLE
Theme breaks with Roam Masonry 

### ISSUE THREAD

**Issue by mridulaecon** [rcvd/roam-css-system#34]
Started using the dark theme. Had to stop using Roam Masonry for the theme to work properly. Details of Roam Masonry here: https://github.com/GitMurf/masonry-vanilla

**Comment by rcvd** [comment]
Just checked it and it seems to be working for me. Could you please check again with reloading your graph?

![Screenshot 2021-06-27 at 18 12 27](https://user-images.githubusercontent.com/12938875/123551731-51e36500-d773-11eb-9637-3b49fe3aefd4.png)

**Comment by mridulaecon** [comment]
Will check again and let you know. I tried the dark theme. Not sure if that
makes a difference. But will try again.
