### ISSUE TITLE
Variable for tags hover? 

### ISSUE THREAD

**Issue by edshamis** [rcvd/roam-css-system#35]
Is there hover variant for --co-tags?

**Comment by rcvd** [comment]
Will add this. Just the co?

**Comment by rcvd** [comment]
Fixed in latest version

**Comment by edshamis** [comment]
Thanks! Maybe you can consider adding
BC, BD, SD, FF, FS, FW, TD  + hover for everyone
for tags as well.
They seem to be useful for tags customizations which people tend to like in
roam

And one more question: what's the variable for 'v' color inside checkmark?

**Comment by rcvd** [comment]
Reopened for adding additional modifiers for tags.

I added a new modifier for the mark of the checkmark:

```
:root {  
    --bt-checkmark__mark--checked: 0px;  
    --br-checkmark__mark--checked: 2px solid var(--cl-gray-900);  
    --bb-checkmark__mark--checked: 2px solid var(--cl-gray-900);  
    --bl-checkmark__mark--checked: 0px;
}

@media (prefers-color-scheme: dark) {  
  :root {
    --bt-checkmark__mark--checked: 0px;    
    --br-checkmark__mark--checked: 2px solid var(--cl-gray-50);
    --bb-checkmark__mark--checked: 2px solid var(--cl-gray-50);
    --bl-checkmark__mark--checked: 0px;
  }
}
```

**Comment by rcvd** [comment]
Added additional modifier for tags
