### ISSUE TITLE
Theme breaks with Mixed Text Direction 

### ISSUE THREAD

**Issue by edshamis** [rcvd/roam-css-system#36]
c3founder's [Mixed Text Direction extension](https://c3founder.github.io/Roam-Enhancement/#mixed-text-direction)  stopped to work with your extension. It used to work yesterday or before, I don't remember exactly

**Comment by rcvd** [comment]
Just tested and it seems working for me:

<img width="824" alt="Screenshot 2021-06-27 at 18 07 59" src="https://user-images.githubusercontent.com/12938875/123551553-9e7a7080-d772-11eb-9262-14cb66721960.png">

<img width="740" alt="Screenshot 2021-06-27 at 18 07 16" src="https://user-images.githubusercontent.com/12938875/123551535-8f93be00-d772-11eb-8d66-e25dd71d7fa2.png">

**Comment by edshamis** [comment]
כל הכבוד!
It works in the light version but not in the dark one

**Comment by rcvd** [comment]
Works for mit all three variants (auto, forced light and forced dark):

<img width="1676" alt="Screenshot 2021-06-27 at 18 53 41" src="https://user-images.githubusercontent.com/12938875/123552963-12b81280-d779-11eb-9941-d595b34423b0.png">

**Comment by edshamis** [comment]
My fault, added custom css before c3founder's plugin
Sorry for bothering you
