### ISSUE TITLE
Customise global fonts

### ISSUE THREAD

**Issue by smillunchick** [rcvd/roam-css-system#38]
Hello! What variable would I change to customise global fonts?

Thanks!

**Comment by rcvd** [comment]
https://roamresearch.com/#/app/css-system/page/miNmgHbby

**Comment by smillunchick** [comment]
I saw that but the div wasn't working to change anything but the tooltip font. I added this to the theme: 

.rm-block-text {
  font-family: "Helvetica Neue", "Courier New", monospace !important;
}

**Comment by rcvd** [comment]
I'll look into that - thanks for informing me

**Comment by rcvd** [comment]
I just double checked and the div block will still modify most of the fonts as described.

<img width="1027" alt="Screenshot 2021-07-01 at 17 41 36" src="https://user-images.githubusercontent.com/12938875/124152240-a64c5480-da93-11eb-9c27-442df2c004a4.png">

**Comment by yigothu** [comment]
Something seems to have broken over the last two days. Customising the fonts with 
```
:root {
    --ff-div: new font 
   --ff-page__title: new font
}
```
no longer has any effect.

**Comment by rcvd** [comment]
Yes, I had to add another CSS selector (--ff-main) for my new lesswrong theme. 

<img width="739" alt="Screenshot 2021-07-05 at 10 55 03" src="https://user-images.githubusercontent.com/12938875/124445055-7fd23600-dd7f-11eb-8129-9bae548c712d.png">
