### ISSUE TITLE
Formatting of structured list composed of block refs and blocks

### ISSUE THREAD

**Issue by shawnyeager** [rcvd/roam-css-system#41]
I'm unsure if this can be smoothed out, but the below screenshot shows the slightly bumpy indentation. Thanks.

<img width="114" alt="Screen Shot 2021-07-06 at 11 50 56 AM" src="https://user-images.githubusercontent.com/980297/124620276-3a8e3100-de71-11eb-9a20-2b783b52d703.png">

**Comment by rcvd** [comment]
The numbers could be a bit higher, but I can't reproduce your bumpy indentation. This looks really weird. Could you show a screenshot of the original blocks?

<img width="304" alt="Screenshot 2021-07-06 at 17 08 28" src="https://user-images.githubusercontent.com/12938875/124624046-d2dde300-de7c-11eb-8e00-4ec9c862e4b1.png">

**Comment by rcvd** [comment]
Are you using any other plugins or CSS customizations?

**Comment by shawnyeager** [comment]
Here's a test page:

<img width="436" alt="Screen Shot 2021-07-07 at 9 59 55 AM" src="https://user-images.githubusercontent.com/980297/124731393-16326300-df0a-11eb-9e52-6ce80e86659b.png">

All other CSS is disabled. I do have roam42 installed.

**Comment by shawnyeager** [comment]
Ok, so it's not your theme. I've disabled or deleted all CSS, Javascript, and reset all user settings, and the odd formatting is still happening. It hadn't occurred to me that it was outside the theme. I'll close this, but report back if/when I figure it out. Sorry for the false alarm.
