### ISSUE TITLE
iA Quattro Dark Mode Customization seems to have some errors

### ISSUE THREAD

**Issue by hugiselephant** [rcvd/roam-css-system#45]
Loving your CSS system

Thank you for all the detailed work you have put into this.
I am using the iA Writer Quattro theme (Auto-switch) and noticed the customization wasn't being applied in the dark theme.

<img width="556" alt="Screen Shot 2021-07-10 at 3 23 53 PM" src="https://user-images.githubusercontent.com/35466673/125177790-91f31080-e193-11eb-9951-c488886a1280.png">

When I change 
`root:` to  `:root` it seems to work

I think all of the dark mode has this issue.

I also noticed in the forced dark mode customization that there are some extra brackets that are causing issues. When I removed the extra brackets they worked. 

<img width="560" alt="Screen Shot 2021-07-10 at 3 33 10 PM" src="https://user-images.githubusercontent.com/35466673/125177882-4d1ba980-e194-11eb-9290-60196ce0e7e3.png">

**Comment by rcvd** [comment]
Awesome, thanks a lot for your report. It's all fixed now and the blocks should be aligned too.
