### ISSUE TITLE
I can't change the general text font

### ISSUE THREAD

**Issue by manfrombar** [rcvd/roam-css-system#46]
<img width="896" alt="CleanShot 2021-07-13 at 13 38 21@2x" src="https://user-images.githubusercontent.com/16494529/125445792-c672f702-21d7-4a39-8ab4-b770d9853390.png">

I would like to keep the iA Quattro theme except the font text, I would prefer the "Lato", sans-serif;
I have included the div/normal code and change it the font, but it doesn't work.
I would appreciate if you can help me.
Thanks

**Comment by rcvd** [comment]
Try changing the main-variables. I added them when I created the LessWrong-theme. The code you use for changing the page title should work.

<img width="723" alt="Screenshot 2021-07-13 at 17 51 02" src="https://user-images.githubusercontent.com/12938875/125484168-037b2fa2-3a18-4b56-9cd6-0ccc534e61ec.png">

**Comment by rcvd** [comment]
I have documented that in the [FAQ](https://roamresearch.com/#/app/css-system/page/miNmgHbby)
