### ISSUE TITLE
Changing font size of headings

### ISSUE THREAD

**Issue by manfrombar** [rcvd/roam-css-system#48]
<img width="1127" alt="CleanShot 2021-08-07 at 15 53 52@2x" src="https://user-images.githubusercontent.com/16494529/128602679-10a2ca09-01b2-42b5-b88a-9606db6624d9.png">

I can't change the font size of h1, h2 and h3. Can you help me? I am changing values, and nothing happens.
Great new Things Theme. How I can delete underline of h2, h3?

**Comment by rcvd** [comment]
Just change the `--fs-level1` parameter to something larger or bigger (e.g. 0.9em or. 1.2em).

If you want to change the heading of the log page chose the variables for `log-page/h1`
