### ISSUE TITLE
Special design for specific tags

### ISSUE THREAD

**Issue by manfrombar** [rcvd/roam-css-system#49]
Hello again, sorry to trouble you!
How can I set up a special design for specific tags, like "tag:important"?
I know how to do it as a CSS format, but I would like to do it into your system, for hover, normal and dark options.
By the way, your system is amazing. Thanks a lot!!!!!

**Comment by rcvd** [comment]
This is how you would create a special formatting for a tag 'evergreen'

    span.rm-page-ref--tag[data-tag='evergreen'] {
        background-color:     transparent;
        border-top:           1px solid var(--cl-green-500);
        border-right:         1px solid var(--cl-green-500);
        border-bottom:        1px solid var(--cl-green-500);
        border-left:          1px solid var(--cl-green-500);
        border-radius:        3px;
        color:                var(--cl-green-500);
        padding:              3px;
    }

    span.rm-page-ref--tag[data-tag='evergreen']:hover {
        background-color:     transparent;
        border-top:           1px solid var(--cl-green-700);
        border-right:         1px solid var(--cl-green-700);
        border-bottom:        1px solid var(--cl-green-700);
        border-left:          1px solid var(--cl-green-700);
        border-radius:        3px;
        color:                var(--cl-green-700);
        padding:              3px;
    }
