### ISSUE TITLE
H3 is italicized

### ISSUE THREAD

**Issue by c-chae** [rcvd/roam-css-system#5]
h3 tag (###) is italicized. see gif below:

![CleanShot 2021-06-13 at 16 46 11](https://user-images.githubusercontent.com/57276522/121822844-f4c1bc80-cc66-11eb-960f-465ec21fd0b7.gif)

**Comment by rcvd** [comment]
What would you suggest as a better default for h3? I personally dislike different font sizes in Roam Research for Headings, therefore I tried to just use bold, italic, and uppercase. But I'm open to suggestions.

**Comment by c-chae** [comment]
I think it's not the best design choice since there is already
italicized format (__text__). I thought it was italicized text but found
out it was an H3 (###). 

–Chris

On June 14, 2021, jeff ***@***.***> wrote:
> What would you suggest as a better default for h3? I personally
> dislike different font sizes in Roam Research for Headings, therefore
> I tried to just use bold, italic, and uppercase. But I'm open to
> suggestions.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rcvd/roam-css-system/issues/5#issuecomment-
860665972>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ANU7Q2RJJ6B7ICZ55VRPM3DTSX4V5ANCNFSM46UD357Q>.

**Comment by battlingthegods** [comment]
I like it the way it is, _but_ possible solutions might be using a different color (iA Writer's blue maybe?), letter-spacing or using a border-style property.

**Comment by rcvd** [comment]
Changed to different sizes (1.4em, 1.2em, 1em). But this can be easily customized in the finale version
