### ISSUE TITLE
How to change the color of roam-block-container

### ISSUE THREAD

**Issue by Alex-roam** [rcvd/roam-css-system#51]
Hi,
How can I change the color of a specific block container?

For example, I want change the background color of the #WeeklyQ and all its child blocks to var(--cl-gray-300)

I tried the following, but it doesn't seem to work:

.roam-block-container[data-page-links*='WeeklyQ'] {
	background-color:  var(--cl-gray-300);
}

Thanks for your great work! Regards, Alex

**Comment by rcvd** [comment]
Hi there, 

a funny idea you had and here is how it works:

    .roam-block-container[data-page-links*='WeeklyQ'] .rm-block-children .roam-block {
         background-color: var(--cl-green-100);
    }

This leads to something like this:

<img width="711" alt="Screenshot 2021-08-20 at 12 57 57" src="https://user-images.githubusercontent.com/12938875/130223471-cad2bcfe-22cc-44f4-959e-f37eea4fff06.png">

Is this what you were trying to achieve?

(Btw. if you made that generous donation via PayPal - thanks a lot, much appreciated!)

Alex

**Comment by Alex-roam** [comment]
<div></div><div>Hi there, 
<br/>
<br/>a funny idea you had and here is how it works:
<br/>
<br/>    .roam-block-container[data-page-links*='WeeklyQ'] .rm-block-children .roam-block {
<br/>         background-color: var(--cl-green-100);
<br/>    }
<br/>
<br/>This leads to something like this:
<br/>
<br/>&lt;img width="711" alt="Screenshot 2021-08-20 at 12 57 57" src="https://user-images.githubusercontent.com/12938875/130223471-cad2bcfe-22cc-44f4-959e-f37eea4fff06.png"&gt;
<br/>
<br/>Is this what you were trying to achieve?
<br/>
<br/>(Btw. if you made that generous donation via PayPal - thanks a lot, much appreciated!)
<br/>
<br/>Alex
<br/>
<br/>-- 
<br/>You are receiving this because you authored the thread.
<br/>Reply to this email directly or view it on GitHub:
<br/>https://github.com/rcvd/roam-css-system/issues/51#issuecomment-902612353</div>
