### ISSUE TITLE
Issues with Apple Light Theme

### ISSUE THREAD

**Issue by Yulin-Rog** [rcvd/roam-css-system#52]
Dear Alexander,

Thank you for your efforts on the Apple Theme :) Great work and very appreciated!

But I'm finding some issues with the top sidebar as it appears all in grey, not sure if I did something wrong, or it's a bug. And I'm not sure how to fix it. 

![Screen Shot 2021-08-25 at 8 37 26 AM](https://user-images.githubusercontent.com/74748709/130707580-2f9ea76a-3e98-434a-8697-bb215424f66a.png)

I'm using the Roam desktop version, on a macOS Catalina 10.15.7 device. 

Many thanks in advance :)

**Comment by rcvd** [comment]
Haven't seen this before using the desktop client on Big Sur. Have you tried using Roam in your browser and is it working there? Have you tried a "Force Reload"? Have you tried uninstalling and reinstalling your desktop app? If all this doesn't work try adding a block with this content under the @import on your roam/css page:

    .roam-main > .rm-files-dropzone {
        background-color: rgba(255,255,255,1);
        -webkit-backdrop-filter: none;
        backdrop-filter: none; 
     }

     @media(prefers-color-scheme: dark) {
        .roam-main > .rm-files-dropzone {
            background-color: rgba(0,0,0,1); 
        }
    }

    .rm-topbar, .rm-topbar .bp3-input, .rm-topbar input[type=search] {
        background: rgba(255,255,255,1);
    }

    @media(prefers-color-scheme: dark) {
        .rm-topbar, .rm-topbar .bp3-input, .rm-topbar input[type=search] {
            background: rgba(0,0,0,1);
        }
    }

**Comment by rcvd** [comment]
Should be fixed now
