### ISSUE TITLE
Bg window color (bear)

### ISSUE THREAD

**Issue by yadhu96** [rcvd/roam-css-system#59]
The inline ref bg window color doesnt stand out. Would be nice if u could change it a bit

![2834A9C7-AF69-41D4-8F23-1DB777F4DB33](https://user-images.githubusercontent.com/68982904/137850155-ff897ed2-f4c2-473a-b6e5-973840a684e0.jpeg)

**Comment by rcvd** [comment]
Should be fixed now, let me know if you are still missing something.
