### ISSUE TITLE
Command palette text disappears under selector box (Bear)

### ISSUE THREAD

**Issue by natestell** [rcvd/roam-css-system#60]
The selector box in the command palette is blue, but the text in the command palette remains black, which makes it barely readable. I assume it's an easy tweak, since in the Help menu the text switches to white when the selector box covers it.

![image](https://user-images.githubusercontent.com/20291888/138006783-b9969ada-3291-4be4-8c43-ff2f9b745f2e.png)

**Comment by rcvd** [comment]
Should be fixed now, let me know if you have any other issues.

**Comment by natestell** [comment]
Cool, thanks!
