### ISSUE TITLE
Dark Mode: not enough contrast between text and cursor highlight color

### ISSUE THREAD

**Issue by natestell** [rcvd/roam-css-system#61]
<img width="925" alt="Screen Shot 2021-10-24 at 9 36 27 AM" src="https://user-images.githubusercontent.com/20291888/138596674-72cf5e19-3034-4a92-8f96-d50125aaee3a.png">

**Comment by rcvd** [comment]
Can't reproduce - looks fine on my side. Please re-open the issue if you still have the problem.

<img width="761" alt="Bildschirmfoto 2021-11-16 um 20 51 46" src="https://user-images.githubusercontent.com/12938875/142055818-d0920bde-4ae9-4b7f-824e-87a1c18aecb2.png">
.

**Comment by natestell** [comment]
Not sure why it presents differently on your end than mine. 

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/20291888/142070308-e3593a14-e2b0-49ff-94df-30b7a8f44bf9.png">

**Comment by natestell** [comment]
Couldn't figure out how to reopen. Also, not sure why it presents
differently on your end than mine.

[image: 🤷‍♂️]
