### ISSUE TITLE
CSS variables for codeblock don't work correctly

### ISSUE THREAD

**Issue by kdnk** [rcvd/roam-css-system#62]
Like https://roamresearch.com/#/app/css-system/page/Uhx1ow4B2, it looks like CSS variables for codeblock haven't worked properly. I have this situation for 1 ~ 2 days.

<img width="500px" src="https://user-images.githubusercontent.com/15260226/141403076-a164a24e-bd24-4bd8-a4ae-546cbca453e2.png">

**Comment by joshbrake** [comment]
I am also seeing this same thing and think that it is related to the updates to the code block including the new language chooser popup at the bottom right of the code and the left sidebar on code blocks. I think the selectors from lines 173-194 in `roam-css-system.css` are the ones that need to be updated to cover the new elements.

https://github.com/rcvd/roam-css-system/blob/4dcaa808264345826416db0f5c7a4df5923b2669/internal/roam-css-system.css#L173

**Comment by kdnk** [comment]
@joshbrake Thanks for your investigation.
FYI: I realized it's fine somehow for the browser version, but the issue seems to be still there on the desktop version...

**Comment by kdnk** [comment]
@rcvd Thanks for working on this, but this problem seems not to be fixed yet.
The background color of the code block is still while even when we set bear-dark.

**Comment by rcvd** [comment]
Should be better now, please check again. Not quite happy with the solution, the unicode selectors causing trouble for my css system.

**Comment by kdnk** [comment]
@rcvd Thanks. It looks fine than before. But We can still see the wrong color for active line. We might have to override the following style as well.

```css
.cm-focused .cm-activeLine {
    background-color: #f3f9ff !important;
}
```

![](https://user-images.githubusercontent.com/15260226/141752254-9b8fd5a1-2355-465c-8a22-b336dac5b34e.png)

**Comment by rcvd** [comment]
Should be fixed now, please check. Syntax highlight colors will be changed as soon as Roam Research has enabled token classnames in code mirror again.

**Comment by kdnk** [comment]
Thank you so much! Looks better now!

FYI:
I realized we might not be able to change the caret color in the code block. you might add a CSS variable for that.
![CleanShot 2021-11-17 at 09 14 15@2x](https://user-images.githubusercontent.com/15260226/142086349-99b17e03-53ce-40fe-8201-c4174b99de2b.png)

**Comment by rcvd** [comment]
Added an appropriate caret color for all themes. Should be fine now.
