### ISSUE TITLE
Can't override Headings (H1,H2,H3)

### ISSUE THREAD

**Issue by amrmjd** [rcvd/roam-css-system#63]
Hi there.. using the Quattro Dark theme (https://rcvd.github.io/roam-css-system/themes/quattro_dark.css) and tried to override H1 and it doesn't seem to work. Screenshot from my roam/css page:

<img width="1154" alt="roam_css" src="https://user-images.githubusercontent.com/3620335/142026929-c7466fe4-b69b-4591-b097-c3f36008b71f.png">

**Comment by rcvd** [comment]
Remove the dash (#) in front of the color. You also don't need the !important.

**Comment by amrmjd** [comment]
Well, that's embarrassing. I added !important thinking somehow i had randomly had it overridden somewhere else. Removed the # and the !important and it works great. Thanks for the quick response, and thank you for making this available. Happy to contribute to support your great work.

**Comment by rcvd** [comment]
Thanks for your contribution - much appreciated :)
