### ISSUE TITLE
Apple theme - extra line after the first query result

### ISSUE THREAD

**Issue by DevonHJames** [rcvd/roam-css-system#65]
There's a minor cosmetic issue with the Apple theme. Whenever I create a query, the first search result contains an empty additional line between it and the second search result. It doesn't impede functionality in any way, but I do find it bothersome to look at :) 

<img width="574" alt="Screen Shot 2021-12-15 at 9 40 29 AM" src="https://user-images.githubusercontent.com/84698020/146206758-e015c2d0-21d2-4112-8544-5bff90f67a22.png">

**Comment by rcvd** [comment]
Should be fixed with the latest update. Thanks for the catch!
