### ISSUE TITLE
Themes prevent arrow navigation of smartblocks pop-up

### ISSUE THREAD

**Issue by MarketHubb** [rcvd/roam-css-system#67]
_(I've tested this with both the Apple and Bear themes enabled, and all other custom CSS turned off)_

The ability to navigate the SmartBlock selector pop-up (xx) with the arrow keys on your keyboard doesn't work when a theme is enabled.

https://capture.dropbox.com/YY8j2PMj6ZzHCjMY

**Comment by rcvd** [comment]
Is this part of a plugin / extension?
