### ISSUE TITLE
page__link  styling

### ISSUE THREAD

**Issue by chasinglucid** [rcvd/roam-css-system#69]
I want all of my page links to be bold, but --fw-page__link doesn't change anything. I also can't increase the size. What can I do?

Thanks in advance!
Jen

**Comment by rcvd** [comment]
I've added the attributes you need to the CSS System, it works now as you expect it. Let me know if you are missing other modifications. 

<img width="831" alt="Bildschirmfoto 2022-02-10 um 06 45 58" src="https://user-images.githubusercontent.com/12938875/153345282-ead3d241-8f4c-4a46-9272-bb50cf03c948.png">
.
