### ISSUE TITLE
Fonts not loading

### ISSUE THREAD

**Issue by eduardoi** [rcvd/roam-css-system#71]
For the past several days I'm noticing that some resources are not loading  at all.  
Today I have "Request time out" for all fonts: https://fonts.rcvd.io for the Quattro theme.
Other days, https://rcvd.github.io/roam-css-system fails as well.
It's a shame because I like a lot what you have done, but as I said, for the past several weeks sometimes it works sometimes it doesnt.
I tryed to follow all links directly on a browser and I can see timeouts and in general very slow responses most of the times.
Hope you find the issue.
Thanks!

**Comment by rcvd** [comment]
There was a server outage on rcvd.io which is fixed now so fonts should be loading again.

I'm not aware of any GitHub Issues, please check if everything is working as expected again.
