### ISSUE TITLE
Link to CSS system blocked by bit.ly

### ISSUE THREAD

**Issue by fsvehla** [rcvd/roam-css-system#73]
https://bit.ly/roam-css-sys is blocked

Warning: This URL has been blocked by Bitly's systems as potentially harmful.

We recommend you close your browser window and notify the person who sent you the link.

**Comment by rcvd** [comment]
Thanks for the report, have contacted bit.ly and I'm waiting for a resolution. Meanwhile the site behind it can be reached here: https://roamresearch.com/#/app/css-system/page/MeO4cyd--

**Comment by rcvd** [comment]
Updated the link in the readme to https://roamresearch.com/#/app/css-system/page/MeO4cyd-- because bit.ly doesn't answer my request.

**Comment by rcvd** [comment]
It's working again
