### ISSUE TITLE
Craft Search Bar

### ISSUE THREAD

**Issue by msf999** [rcvd/roam-css-system#74]
Thanks for the amazing work on these themes. Is there a way to only get the CSS for the search bar of the Craft theme?

**Comment by rcvd** [comment]
I have created a gist for this: https://gist.github.com/rcvd/f6758b2174387291586e1a54575b4c09. Just copy it into a CSS block on your roam/css page or below a {{roam/css}} entry.

My next version of the Roam CSS System will be completely modular.

**Comment by msf999** [comment]
Awesome! Thank you so much! The gist work well except that it hides the search icon (🔍)- not a big deal since I use the keyboard shortcut anyway.
