### ISSUE TITLE
Lesswrong: collapsed blocks with children have misaligned bullets

### ISSUE THREAD

**Issue by graemesi** [rcvd/roam-css-system#81]
In the attached screenshot, the middle block has children and is collapsed. For this middle block:

1. The bullet is misaligned both vertically and horizontally

2. The bullet doesn't look any different from standard bullets - I think LessWrong's theme previously had collapsed bullets that looked a little more distinctive so you can see there are child blocks? _(I don't have an older version of the theme to compare to see if my recollection is correct)_

<img width="428" alt="blocks-children" src="https://user-images.githubusercontent.com/8223803/180174483-e6003fa5-3662-445c-be76-0f18185456d5.png">

**Comment by rcvd** [comment]
Should be fixed now. Let me know if you are missing something else.

**Comment by graemesi** [comment]
Yes, it's fixed thank you
