### ISSUE TITLE
[Craft] font size suddenly much larger (too large)

### ISSUE THREAD

**Issue by lurw13** [rcvd/roam-css-system#88]
Title says it all, fonts have suddenly become much bigger, on all platforms that I use (MacOS, iOS, Windows)

**Comment by rcvd** [comment]
Can't reproduce. Do you have any other CSS scripts running? Is your Zoom Level set to 100%? Please check if https://roamresearch.com/#/app/css-system shows the same problem.

**Comment by lurw13** [comment]
![Unbenannt](https://user-images.githubusercontent.com/75320133/184077835-b6192e40-21ae-4353-8e2d-96b367453b36.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/75320133/184077845-2c6dcce8-04b4-4a0c-9f73-1ab19abbaffc.PNG)

See the two pics, with CSS deactivated (plain text), the body font size is smaller.

**Comment by rcvd** [comment]
I personally find the Roam Research Font too small so I made them a bit bigger in the Craft theme. You can customize the font size by adding a new CSS block and put something like this in:

    :root { 
      --fs-div: 13px;
    }


More detailed instructions are here: https://bit.ly/roam-css-sys

Beware: The CSS System is under heavy development to become a plugin where settings can be customized via UI.

**Comment by lurw13** [comment]
Perfect, merci!
