### ISSUE TITLE
Issues with native Roam menu items and message panels - Things theme

### ISSUE THREAD

**Issue by MarketHubb** [rcvd/roam-css-system#89]
There's a lack of text contrast in roam menu items. See text color not turning white on :hover for the bp3-menu-item class of elements. No background color on popup message panels (bp3-toast-message).

<img width="1510" alt="roam-bp3-menu-item(hover)" src="https://user-images.githubusercontent.com/5453922/184872688-b05edd54-07b1-48d0-950e-e73a93cb4c26.png">

<img width="1510" alt="roam-bp3-toast-message" src="https://user-images.githubusercontent.com/5453922/184872694-0a3d0520-1130-47ff-ba4c-db2f7e49d816.png">

**Comment by rcvd** [comment]
Fixed with latest version
