### ISSUE TITLE
Background for ZoteroRoam API too bright in dark mode

### ISSUE THREAD

**Issue by JoBBurt** [rcvd/roam-css-system#9]
The ZoteroRoam API is an extension in Roam used by myself and other researchers. I attached screenshots to the issue of the display in Roam and the code for the block when inspecting the element. 

![image](https://user-images.githubusercontent.com/61160408/121914640-7285d680-cd00-11eb-8901-1ebf511a30ee.png)
![image](https://user-images.githubusercontent.com/61160408/121914951-bbd62600-cd00-11eb-9c88-5ca5fa196dc8.png)

**Comment by rcvd** [comment]
Should be way better now. Let me know if you see additional issues as I don't use the Zotero plugin very often.

**Comment by JoBBurt** [comment]
Oh wow, that made it way better. Thank you for fixing this!
