### ISSUE TITLE
[Craft] Transparent messages and prompts

### ISSUE THREAD

**Issue by kvistgaard** [rcvd/roam-css-system#90]
Here's an example
![image](https://user-images.githubusercontent.com/7572721/185731087-d514694c-c6ea-4cee-a70a-43f96ebeb0ac.png)

But it's worse when there is a choice to be made and the button are invisible

![image](https://user-images.githubusercontent.com/7572721/185731143-b5901c6a-8ca9-435a-809d-9ec7f6a231f2.png)

**Comment by rcvd** [comment]
Should be fixed with latest commit
