### ISSUE TITLE
Hover tooltip text very difficult to read in Apple theme

### ISSUE THREAD

**Issue by axelav** [rcvd/roam-css-system#97]
Text is too closely matches the background to be readable. These tooltips appear in various places when you hover - block bullets & reference counts, most of the top bar icons/buttons, etc.

<img width="213" alt="Screen Shot 2022-10-12 at 1 02 43 PM" src="https://user-images.githubusercontent.com/59404/195404487-66a269d0-192d-4c79-91b7-d59b4893183b.png">

<img width="322" alt="image" src="https://user-images.githubusercontent.com/59404/195404689-ba248dfa-48fc-470e-91d1-b7cd48bd0a92.png">

**Comment by rcvd** [comment]
Thanks for reporting this - this CSS System is superseded by the new Roam Studio Plugin which is available on Roam Depot. There isn't the Apple theme available yet but you can change the font of the Quattro theme to "System Font". The next update contains the "Craft Theme" and waits for confirmation by Roam Research to be released soon.

**Comment by axelav** [comment]
Thanks @rcvd - I'll check that out. I followed the docs here and dropped in some custom CSS below the import that works well for me now. Thanks for the great work on the themes!
