### ISSUE TITLE
In the Things theme there are references to two missing files

### ISSUE THREAD

**Issue by cori** [rcvd/roam-css-system#98]
- https://rcvd.github.io/roam-css-system/internal/common/fixes.css
- https://rcvd.github.io/roam-css-system/internal/things/common/fonts.css

Both 404, and neither appear in their corresponding places in the repo.

<img width="882" alt="image" src="https://user-images.githubusercontent.com/46317/210298239-a8255673-6009-45cf-af4c-5339cd0f12e9.png">

**Comment by rcvd** [comment]
The Roam CSS System is deprecated and replaced by the Roam Studio Plugin. You can find it within the Roam Depot under Settings → Roam Depot → Community Extensions.

The things theme is not part of it yet but you can a similar look using the Craft Theme with some modifications in the settings.

**Comment by cori** [comment]
Understood; personally I'd prefer to keep theming out of extensions for now so I'll adapt this css as best I can; these seem pretty minor (and maybe are duplicates of the same resources in the "right" locations from the imports). Thanks!
